#cloud-config
hostname: vps-{{name}}
manage_etc_hosts: true
users:
  - name: root
    plain_text_passwd: "{{root_password}}"
    lock_passwd: false
    ssh_pwauth: true
ssh_pwauth: true
chpasswd:
  expire: false
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQ...
